# ADSK 2021 Wordpress playbook - Dominik Borowy

---
- hosts: servers
  become: true
  vars_files:
    - vars/default.yml
  
  tasks:    
    - name: Install prerequisites
      ansible.builtin.package:
        name:
          - apache
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
        state: present
    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ apache ]